### PR TITLE
Move code back to MarkTiedemann/fullscreen

### PR DESCRIPTION
**Pull request by th0rgall**
A PR to move my improvements into the original repo.

Main changes:
1. Refactor from <all_urls> permission to the less intrusive activeTab permission
2. Refactor custom key listeners to out-of-the-box WebExtension Command API shortcuts

There are [known issues](https://github.com/th0rgall/fullscreen/issues/1#issuecomment-583044550) to work on.

If I find time I'll make a small build script that spits out a working Firefox & Chrome release.

### CODE REVIEW

**Comment by th0rgall** [comment]
Hey @MarkTiedemann, I changed the default shortcut to Cmd/Ctr + Shift + I to fix https://github.com/th0rgall/fullscreen/issues/1. Works on Firefox & Chrome for me (macOS).

It wasn't used anywhere on the shortcut list you mentioned so I hope it doesn't clash with anything else. Are you able test on Windows/Linux?

**Comment by MarkTiedemann** [comment]
@th0rgall I'm kind of speechless - that's amazing work. Thanks a lot!

I don't have time right now, but I will take time to review, hopefully merge and release this PR at the weekend.

----

I feel like, since you have probably done more work on this extension already than I have, it may be appropriate to move it to your GitHub account rather than mine. I'd also be fine with creating a new GitHub organization for it, or just keeping it under my account, of course.

What's your preference?

**Comment by MarkTiedemann** [comment]
> Are you able test on Windows/Linux?

I will be able to test on my Windows laptop at the weekend. Linux, no.

**Comment by th0rgall** [comment]
@MarkTiedemann 
> Thanks a lot!

You're welcome. I care about this full screen functionality 😄

> I will be able to test on my Windows laptop at the weekend. Linux, no.

Cool, thanks!

> I feel like, since you have probably done more work on this extension already than I have, it may be appropriate to move it to your GitHub account rather than mine

That's ok for me, I'm willing to maintain it further.

Just 1 thing: since you have 70 users on [your published addon](https://addons.mozilla.org/en-US/firefox/addon/fullscreen-any-site/?src=search) on Firefox, I think it's important that we push my improvements to them as well (+ update the store listing). They are actually the only users atm. 

You could either update it yourself, or add me as an "author" to your extension in the Mozilla Addon Developer Hub. I guess I can then upload the new version and do changes.

**Comment by MarkTiedemann** [comment]
>  I care about this full screen functionality 😄

You have renewed my interest in it as well. :)

> I'm willing to maintain it further.

Same for me.

> You could either update it yourself, or add me as an "author" to your extension in the Mozilla Addon Developer Hub.

I think I need to know your email address to add you to the Developer Hub account. I could not find it on your website. If you want to keep it private, please send it to my email `www.marktiedemann@gmail.com`.

I have invited you to this repository as well. I think, for now, I'd like to keep the code here.

**Comment by MarkTiedemann** [comment]
LGTM.

**Comment by MarkTiedemann** [comment]
Just had some trouble releasing the new version - somehow `web-ext` got stuck and created some sort of partial version `0.3.3` (and since you can't publish `0.3.3` twice, I had to bump to `0.3.4`). Anyways, after updating `web-ext`, signing and uploading the extension worked fine again. `0.3.4` is now released. :)

**Comment by th0rgall** [comment]
Nice! I hadn't used `web-ext` myself, the Mozilla Developer Hub web UI accepts unsigned .zips.

**Comment by MarkTiedemann** [comment]
> the Mozilla Developer Hub web UI accepts unsigned .zips

I didn't know that. Thanks!

**Pull request merged**
